// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/libros": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Libro"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Crea un nuevo libro",
                "parameters": [
                    {
                        "description": "Libro a crear",
                        "name": "libro",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Libro"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.Libro"
                        }
                    }
                }
            }
        },
        "/libros/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Obtiene un libro por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del libro",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Libro"
                        }
                    },
                    "404": {
                        "description": "Libro no encontrado",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Actualiza un libro",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del libro",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "description": "Libro actualizado",
                        "name": "libro",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Libro"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Libro"
                        }
                    }
                }
            },
            "delete": {
                "summary": "Elimina un libro",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del libro",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Libro": {
            "type": "object",
            "properties": {
                "autor": {
                    "type": "string"
                },
                "genero": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "titulo": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API de Libros",
	Description:      "API para gestionar libros (ABM)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
